# Generated by Django 5.0.3 on 2024-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
