# Generated by Django 5.0.3 on 2024-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_tag_order_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="accounts.tag"),
        ),
    ]
