# Generated by Django 5.0.3 on 2024-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_order_tag_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
