# Generated by Django 5.0.3 on 2024-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customer_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_ordered",
            field=models.DateField(null=True),
        ),
    ]
