# Generated by Django 5.0.3 on 2024-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_order_date_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_delivered",
            field=models.DateField(null=True),
        ),
    ]
