# Generated by Django 5.0.3 on 2024-03-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_order_date_delivered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="instock",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
