# Generated by Django 5.0.3 on 2024-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_rename_quantity_product_instock_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
