# Generated by Django 5.0.3 on 2024-03-14 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_customer_user_order_user_product_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
