# Generated by Django 5.0.3 on 2024-03-16 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_product_order_level_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="order_level",
            new_name="reorder_level",
        ),
    ]
