# Generated by Django 5.0.3 on 2024-03-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_rename_order_level_product_reorder_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_image"),
        ),
    ]
