# Generated by Django 5.0.3 on 2024-03-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
