# Generated by Django 5.0.3 on 2024-03-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fullname",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
