# Generated by Django 5.0.3 on 2024-03-16 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
